version: "beta"

app:
  name: "demo"
  host: "35.186.244.102"
  port: "80"
  scheme: "https"

  dashboards:
    Vodafone:
      app: "rot_smart_homes_app"
      name: "smeiling_dashboard_vodafone_demo_v10"

  splunk:
    host: "37.48.244.182"
    port: "8000"
    scheme: "http"
    username: "vodademo"
    password: "b98puxPJinkQ"

  style:
    logos:
      smeiling: "app/SmEILing.png"
      republic: "app/republic_logo.png"
      partner: "app/republic_logo.png"

    stylesheets:
      - "app/content/republic.css"

  deployment:
    repo: "gcr.io/encoded-antler-258511"
