version: "3"

services:
  splunk:
    build:
      context: .
      dockerfile: splunk/Dockerfile
    ports:
      - 5000:5000

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - APP_NAME=vodademo
    depends_on:
       - smeiling

  smeiling:
     build:
      context: .
      dockerfile: smeiling/Dockerfile
     volumes:
       - ./config/:/app/config
