version: "beta"

app:
  name: "{{ app.name }}"
  host: "{{ app.host }}"
  port: "80"
  scheme: "https"

  replicas: 1

  credentials:
    - username: "republic"
      password: "R3public1"

  dashboards:
    Vodafone:
      app: "rot_smart_homes_app"
      name: "smeiling_dashboard_vodafone_demo_v10"

  splunk:
    host: "{{ splunk.host }}"
    port: "{{ splunk.port }}"
    scheme: "http"
    username: "{{ splunk.username }}"
    password: "{{ splunk.password }}"

  style:
    logos:
      smeiling: "img/logos/SmEILing.png"
      republic: "img/logos/republic_logo.png"
      partner: "img/logos/vodafone.png"

    stylesheets:
      - "/app/content/republic.css"

  deployment:
    dockerRepo: "{{ repository }}"
